name: DwarfSpawn
version: 1.0.0
main: com.dwarfspawn.DwarfSpawn
api-version: 1.21
author: MrMeows
description: Плагин для настройки спавна гномов под землей
website: https://github.com/MrMe0ws

commands:
  dwarfspawn:
    description: Команды плагина DwarfSpawn
    usage: /<command> reload
    aliases: [ds, dwarf]

permissions:
  dwarfspawn.reload:
    description: Позволяет перезагружать конфигурацию плагина
    default: op
