name: DwarfSpawn
version: 1.1.0
main: com.dwarfspawn.DwarfSpawn
api-version: 1.21
author: MrMeows
description: Плагин для настройки спавна гномов под землей
website: https://github.com/MrMe0ws

commands:
  dwarfspawn:
    description: Команды плагина DwarfSpawn
    usage: /<command> reload
    aliases: [ds, dwarf]
  rtp:
    description: Телепортирует игрока в случайное место на карте
    usage: /<command> [игрок]
    aliases: []

permissions:
  dwarfspawn.reload:
    description: Позволяет перезагружать конфигурацию плагина
    default: op
  dwarfspawn.rtp:
    description: Позволяет использовать команду /rtp
    default: false
  ds.rtp:
    description: Позволяет использовать команду /rtp (алиас)
    default: false
